name: Build

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-unix:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        nimversion:
          - binary:stable

        os: [ubuntu-latest, macos-latest]
        include:
          - os: ubuntu-latest
            filename: mcsrvstat
            artifact: linux-x64

          - os: macos-latest
            filename: mcsrvstat
            artifact: darwin-x64

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Nim
      uses: iffy/install-nim@v4
      with:
        version: ${{ matrix.nimversion }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Check package validity
      run: nimble check

    - name: Build
      run: nimble build -d:release --accept

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.artifact }}
        path: ${{ matrix.filename }}


  build-windows:
    name: windows-latest
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Nim
      uses: iffy/install-nim@v4
      with:
        version: binary:stable
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Check package validity
      run: nimble check

    - name: Build
      run: nimble build -d:release --accept
