name: Build

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        nimversion:
          - binary:stable
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Nim
      uses: iffy/install-nim@v4
      with:
        version: ${{ matrix.nimversion }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Check package validity
      run: nimble check

    - name: Build (SSL added)
      run: nimble -d:ssl build --accept